# Generated by Django 4.2.4 on 2023-08-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_loan_account_balance_account_name_contribution_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan',
            field=models.IntegerField(default=6300),
        ),
    ]
