# Generated by Django 4.2.4 on 2023-08-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_remove_account_balance_turn_monthlyactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyactivity',
            name='month',
        ),
        migrations.AddField(
            model_name='apply',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyactivity',
            name='aggregate_balance',
            field=models.IntegerField(default=6300),
        ),
        migrations.AlterField(
            model_name='monthlyactivity',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='turn',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
