# Generated by Django 4.2.4 on 2023-08-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_remove_monthlyactivity_month_apply_date_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
