# Generated by Django 4.2.4 on 2023-08-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyactivity',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
