# Generated by Django 4.2.4 on 2023-08-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_loan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='member',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='member',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyactivity',
            name='member',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='turn',
            name='member',
            field=models.CharField(max_length=20),
        ),
    ]
