# Generated by Django 4.2.4 on 2023-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_activitylog_account_admin_alter_apply_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('event', 'event'), ('info', 'info'), ('system', 'system'), ('team', 'team')], max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('sender', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=250)),
                ('read', models.BooleanField(default=0)),
            ],
        ),
    ]
