# Generated by Django 4.2.4 on 2023-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='Welcome Message', max_length=250),
        ),
    ]
