# Generated by Django 4.2.4 on 2023-08-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_notification_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
