# Generated by Django 4.2.4 on 2023-08-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_account_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=20),
        ),
    ]
