# Generated by Django 4.2.4 on 2023-08-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_payloan_alter_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_year',
            field=models.IntegerField(default=2001),
        ),
        migrations.AlterField(
            model_name='apply',
            name='type',
            field=models.BooleanField(default=0),
        ),
    ]
