# Generated by Django 4.2.4 on 2023-09-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0015_contribution_contribution_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
